---
# Keycloak LoadBalancer service (external access)
# Docker Desktop will expose this on localhost:8180 (HTTP) and localhost:9000 (management/health)
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: api-gateway-poc
  labels:
    app: keycloak
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
  - name: http
    port: 8180
    targetPort: 8080
    protocol: TCP
  - name: management
    port: 9000
    targetPort: 9000
    protocol: TCP
